
import React, { useState, useEffect } from 'react';
import { getUsers, getCourses, updateMarks } from '../../services/api';
import { Save } from 'lucide-react';

const TeacherMarksEntry = ({ user }) => {
    const [students, setStudents] = useState([]);
    const [courses, setCourses] = useState([]);
    const [selectedStudent, setSelectedStudent] = useState('');
    const [selectedCourse, setSelectedCourse] = useState('');
    const [examMarks, setExamMarks] = useState('');
    const [assignmentMarks, setAssignmentMarks] = useState('');
    const [message, setMessage] = useState('');

    useEffect(() => {
        const fetchData = async () => {
            try {
                const sData = await getUsers('student', user.dept);
                setStudents(sData);
                const cData = await getCourses(user.dept);
                // In reality, getCourses might fetch by year too, but for teacher we want all dept courses or their own courses
                setCourses(cData);
            } catch (e) {
                console.error("Error fetching data for marks entry", e);
            }
        };
        fetchData();
    }, [user.dept]);


    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!selectedStudent || !selectedCourse) {
            setMessage('Please select student and course.');
            return;
        }

        const courseObj = courses.find(c => c.id === selectedCourse);
        const subjectName = courseObj ? courseObj.name : "Unknown Subject";

        try {
            await updateMarks({
                studentId: selectedStudent,
                courseId: selectedCourse,
                marks: parseFloat(examMarks),
                assignment: parseFloat(assignmentMarks),
                subject: subjectName
            });
            setMessage('Marks updated successfully!');
            setTimeout(() => setMessage(''), 3000);
            setExamMarks('');
            setAssignmentMarks('');
        } catch (e) {
            setMessage('Failed to update marks');
        }
    };

    return (
        <div className="glass" style={{ padding: '2rem', maxWidth: '600px', margin: '0 auto' }}>
            <h2 style={{ marginBottom: '2rem', color: 'var(--primary)' }}>Enter Student Marks</h2>

            <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                <div>
                    <label style={{ display: 'block', marginBottom: '0.5rem', color: 'var(--text-secondary)' }}>Student</label>
                    <select
                        value={selectedStudent}
                        onChange={(e) => setSelectedStudent(e.target.value)}
                        style={{ width: '100%', padding: '1rem', background: 'var(--bg-card)', border: '1px solid var(--glass-border)', borderRadius: '12px', color: 'white', outline: 'none' }}
                    >
                        <option value="">Select Student</option>
                        {students.map((s, idx) => (
                            <option key={idx} value={s.id}>{s.name} ({s.regNo})</option> // Use s.id which is generated by backend
                        ))}
                    </select>
                </div>

                <div>
                    <label style={{ display: 'block', marginBottom: '0.5rem', color: 'var(--text-secondary)' }}>Course</label>
                    <select
                        value={selectedCourse}
                        onChange={(e) => setSelectedCourse(e.target.value)}
                        style={{ width: '100%', padding: '1rem', background: 'var(--bg-card)', border: '1px solid var(--glass-border)', borderRadius: '12px', color: 'white', outline: 'none' }}
                    >
                        <option value="">Select Course</option>
                        {courses.map(c => <option key={c.id} value={c.id}>{c.name} ({c.id})</option>)}
                    </select>
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                    <div>
                        <label style={{ display: 'block', marginBottom: '0.5rem', color: 'var(--text-secondary)' }}>Exam Marks</label>
                        <input
                            type="number"
                            value={examMarks}
                            onChange={(e) => setExamMarks(e.target.value)}
                            placeholder="0-100"
                            min="0" max="100"
                            style={{ width: '100%', padding: '1rem', background: 'var(--bg-card)', border: '1px solid var(--glass-border)', borderRadius: '12px', color: 'white', outline: 'none' }}
                        />
                    </div>
                    <div>
                        <label style={{ display: 'block', marginBottom: '0.5rem', color: 'var(--text-secondary)' }}>Assignment</label>
                        <input
                            type="number"
                            value={assignmentMarks}
                            onChange={(e) => setAssignmentMarks(e.target.value)}
                            placeholder="0-100"
                            min="0" max="100"
                            style={{ width: '100%', padding: '1rem', background: 'var(--bg-card)', border: '1px solid var(--glass-border)', borderRadius: '12px', color: 'white', outline: 'none' }}
                        />
                    </div>
                </div>

                {message && <p style={{ color: message.includes('success') ? 'var(--accent)' : '#ef4444', textAlign: 'center' }}>{message}</p>}

                <button
                    type="submit"
                    style={{
                        marginTop: '1rem',
                        padding: '1rem',
                        background: 'linear-gradient(to right, var(--primary), var(--secondary))',
                        border: 'none',
                        borderRadius: '12px',
                        color: 'white',
                        fontWeight: '600',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        gap: '0.5rem'
                    }}
                >
                    <Save size={20} /> Save Marks
                </button>
            </form>
        </div>
    );
};

export default TeacherMarksEntry;
